In [2]:
# Import Numpy for calculations, matplotlib for charting, and pandas for coding
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

In [21]:
# Save path to data set in a variable
data_file = "../resources/raw/dataSet.csv"
data_file2 = "../resources/raw/counties.csv"

In [22]:
# Use Pandas to read data
data_file_df = pd.read_csv(data_file)
data_file_df.head()

,country_region_code,country_region,sub_region_1,sub_region_2,metro_area,iso_3166_2_code,census_fips_code,date,retail_and_recreation_percent_change_from_baseline,grocery_and_pharmacy_percent_change_from_baseline,parks_percent_change_from_baseline,transit_stations_percent_change_from_baseline,workplaces_percent_change_from_baseline,residential_percent_change_from_baseline
0,US,United States,NaN,NaN,NaN,NaN,NaN,2020-02-15,6.0,2.0,15.0,3.0,2.0,-1.0
1,US,United States,NaN,NaN,NaN,NaN,NaN,2020-02-16,7.0,1.0,16.0,2.0,0.0,-1.0
2,US,United States,NaN,NaN,NaN,NaN,NaN,2020-02-17,6.0,0.0,28.0,-9.0,-24.0,5.0
3,US,United States,NaN,NaN,NaN,NaN,NaN,2020-02-18,0.0,-1.0,6.0,1.0,0.0,1.0
4,US,United States,NaN,NaN,NaN,NaN,NaN,2020-02-19,2.0,0.0,8.0,1.0,1.0,0.0

In [23]:
#Drop NaN's from columns

data_file_df.dropna(inplace=True, subset=["sub_region_1", "sub_region_2"])
data_file_df.head(20)

,country_region_code,country_region,sub_region_1,sub_region_2,metro_area,iso_3166_2_code,census_fips_code,date,retail_and_recreation_percent_change_from_baseline,grocery_and_pharmacy_percent_change_from_baseline,parks_percent_change_from_baseline,transit_stations_percent_change_from_baseline,workplaces_percent_change_from_baseline,residential_percent_change_from_baseline
540,US,United States,Alabama,Autauga County,NaN,NaN,1001.0,2020-02-15,5.0,7.0,NaN,NaN,-4.0,NaN
541,US,United States,Alabama,Autauga County,NaN,NaN,1001.0,2020-02-16,0.0,1.0,-23.0,NaN,-4.0,NaN
542,US,United States,Alabama,Autauga County,NaN,NaN,1001.0,2020-02-17,8.0,0.0,NaN,NaN,-27.0,5.0
543,US,United States,Alabama,Autauga County,NaN,NaN,1001.0,2020-02-18,-2.0,0.0,NaN,NaN,2.0,0.0
544,US,United States,Alabama,Autauga County,NaN,NaN,1001.0,2020-02-19,-2.0,0.0,NaN,NaN,2.0,0.0
545,US,United States,Alabama,Autauga County,NaN,NaN,1001.0,2020-02-20,-8.0,-3.0,NaN,NaN,1.0,2.0
546,US,United States,Alabama,Autauga County,NaN,NaN,1001.0,2020-02-21,-3.0,-2.0,NaN,NaN,3.0,0.0
547,US,United States,Alabama,Autauga County,NaN,NaN,1001.0,2020-02-22,1.0,1.0,NaN,NaN,8.0,NaN
548,US,United States,Alabama,Autauga County,NaN,NaN,1001.0,2020-02-23,0.0,3.0,NaN,NaN,5.0,NaN
549,US,United States,Alabama,Autauga County,NaN,NaN,1001.0,2020-02-24,-2.0,-5.0,NaN,NaN,2.0,1.0
550,US,United States,Alabama,Autauga County,NaN,NaN,1001.0,2020-02-25,10.0,0.0,NaN,NaN,3.0,-1.0
551,US,United States,Alabama,Autauga County,NaN,NaN,1001.0,2020-02-26,17.0,5.0,NaN,NaN,4.0,-1.0
552,US,United States,Alabama,Autauga County,NaN,NaN,1001.0,2020-02-27,14.0,11.0,NaN,NaN,2.0,-2.0
553,US,United States,Alabama,Autauga County,NaN,NaN,1001.0,2020-02-28,12.0,10.0,NaN,NaN,2.0,-2.0
554,US,United States,Alabama,Autauga County,NaN,NaN,1001.0,2020-02-29,21.0,10.0,NaN,NaN,5.0,NaN
555,US,United States,Alabama,Autauga County,NaN,NaN,1001.0,2020-03-01,15.0,13.0,NaN,NaN,3.0,NaN
556,US,United States,Alabama,Autauga County,NaN,NaN,1001.0,2020-03-02,15.0,4.0,NaN,NaN,5.0,-1.0
557,US,United States,Alabama,Autauga County,NaN,NaN,1001.0,2020-03-03,22.0,8.0,NaN,NaN,4.0,-1.0
558,US,United States,Alabama,Autauga County,NaN,NaN,1001.0,2020-03-04,5.0,-4.0,NaN,NaN,3.0,2.0
559,US,United States,Alabama,Autauga County,NaN,NaN,1001.0,2020-03-05,7.0,12.0,NaN,NaN,3.0,1.0

In [43]:
data_file2_df = pd.read_csv(data_file2)
data_file2_df.head()

         City       State             County
0    Portland      Oregon   Multnomah County
1     Medford      Oregon     Jackson County
2       Boise       Idaho         Ada County
3  Sacramento  California  Sacramento County
4     Oakland  California     Alameda County

In [45]:
combined_df = data_file_df[data_file_df["sub_region_1"].isin(data_file2_df["State"])]
combined_df = combined_df[combined_df["sub_region_2"].isin(data_file2_df["County"])]
#combined_df.loc[combined_df["sub_region_2"]=="Sacramento County",:]
combined_df.head()
#combined_df["sub_region_1"].value_counts()
#data_file2_df["County"].tolist()

,country_region_code,country_region,sub_region_1,sub_region_2,metro_area,iso_3166_2_code,census_fips_code,date,retail_and_recreation_percent_change_from_baseline,grocery_and_pharmacy_percent_change_from_baseline,parks_percent_change_from_baseline,transit_stations_percent_change_from_baseline,workplaces_percent_change_from_baseline,residential_percent_change_from_baseline
3739,US,United States,Alabama,Clay County,NaN,NaN,1027.0,2020-02-15,-13.0,2.0,NaN,NaN,NaN,NaN
3740,US,United States,Alabama,Clay County,NaN,NaN,1027.0,2020-02-16,NaN,-6.0,NaN,NaN,NaN,NaN
3741,US,United States,Alabama,Clay County,NaN,NaN,1027.0,2020-02-17,-23.0,8.0,NaN,NaN,-19.0,NaN
3742,US,United States,Alabama,Clay County,NaN,NaN,1027.0,2020-02-18,-17.0,4.0,NaN,NaN,-13.0,NaN
3743,US,United States,Alabama,Clay County,NaN,NaN,1027.0,2020-02-19,-7.0,0.0,NaN,NaN,0.0,NaN

In [1]:
combined_df.to_csv("../resources/clean/Karen_clean.csv")

NameError: name 'combined_df' is not defined

In [35]:
#load the csv
whole_df = pd.read_csv("../resources/clean/Karen_clean.csv")
whole_df

,Unnamed: 0,country_region_code,country_region,sub_region_1,sub_region_2,metro_area,iso_3166_2_code,census_fips_code,date,retail_and_recreation_percent_change_from_baseline,grocery_and_pharmacy_percent_change_from_baseline,parks_percent_change_from_baseline,transit_stations_percent_change_from_baseline,workplaces_percent_change_from_baseline,residential_percent_change_from_baseline
0,3739,US,United States,Alabama,Clay County,NaN,NaN,1027.0,2020-02-15,-13.0,2.0,NaN,NaN,NaN,NaN
1,3740,US,United States,Alabama,Clay County,NaN,NaN,1027.0,2020-02-16,NaN,-6.0,NaN,NaN,NaN,NaN
2,3741,US,United States,Alabama,Clay County,NaN,NaN,1027.0,2020-02-17,-23.0,8.0,NaN,NaN,-19.0,NaN
3,3742,US,United States,Alabama,Clay County,NaN,NaN,1027.0,2020-02-18,-17.0,4.0,NaN,NaN,-13.0,NaN
4,3743,US,United States,Alabama,Clay County,NaN,NaN,1027.0,2020-02-19,-7.0,0.0,NaN,NaN,0.0,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
61760,677767,US,United States,Wyoming,Teton County,NaN,NaN,56039.0,2020-11-06,-45.0,-32.0,-21.0,-61.0,-35.0,NaN
61761,677768,US,United States,Wyoming,Teton County,NaN,NaN,56039.0,2020-11-07,-51.0,NaN,-46.0,-68.0,-44.0,NaN
61762,677769,US,United States,Wyoming,Teton County,NaN,NaN,56039.0,2020-11-08,-53.0,NaN,-55.0,-65.0,-45.0,NaN
61763,677770,US,United States,Wyoming,Teton County,NaN,NaN,56039.0,2020-11-09,-46.0,NaN,-44.0,-54.0,-36.0,NaN
61764,677771,US,United States,Wyoming,Teton County,NaN,NaN,56039.0,2020-11-10,-51.0,NaN,-52.0,-58.0,-40.0,NaN

In [51]:
#make the date column a datetime object
whole_df['date'] = pd.to_datetime(whole_df['date'], format="%Y/%m/%d")

In [63]:
#add a new column that is the month
whole_df["month"] = whole_df["date"].map(lambda x: x.month)
#group on regions and month
grouped_df = whole_df.groupby(["sub_region_1","sub_region_2","month"]).mean()
grouped_df = grouped_df[["retail_and_recreation_percent_change_from_baseline","grocery_and_pharmacy_percent_change_from_baseline","parks_percent_change_from_baseline","transit_stations_percent_change_from_baseline","workplaces_percent_change_from_baseline","residential_percent_change_from_baseline"]]
grouped_df

                                 retail_and_recreation_percent_change_from_baseline  \
sub_region_1 sub_region_2 month
Alabama      Clay County  2                                              -4.153846
                          3                                             -16.680000
                          4                                             -33.000000
                          5                                                    NaN
                          6                                                    NaN
...                                                                            ...
Wyoming      Teton County 7                                              37.354839
                          8                                              42.062500
                          9                                              32.050000
                          10                                             -9.129032
                          11                                            -45.400000

                                 grocery_and_pharmacy_percent_change_from_baseline  \
sub_region_1 sub_region_2 month
Alabama      Clay County  2                                               2.000000
                          3                                               5.461538
                          4                                               7.750000
                          5                                                    NaN
                          6                                                    NaN
...                                                                            ...
Wyoming      Teton County 7                                                    NaN
                          8                                                    NaN
                          9                                                    NaN
                          10                                            -27.000000
                          11                                            -32.000000

                                 parks_percent_change_from_baseline  \
sub_region_1 sub_region_2 month
Alabama      Clay County  2                                     NaN
                          3                                     NaN
                          4                                     NaN
                          5                                     NaN
                          6                                     NaN
...                                                             ...
Wyoming      Teton County 7                                     NaN
                          8                                     NaN
                          9                                     NaN
                          10                              62.666667
                          11                             -27.600000

                                 transit_stations_percent_change_from_baseline  \
sub_region_1 sub_region_2 month
Alabama      Clay County  2                                                NaN
                          3                                                NaN
                          4                                                NaN
                          5                                                NaN
                          6                                                NaN
...                                                                        ...
Wyoming      Teton County 7                                          -0.258065
                          8                                           7.125000
                          9                                          -8.250000
                          10                                        -34.354839
                          11                                        -57.800000

                                 workplaces_percent_change_from_baseline  \
sub_region_1 sub_region_2 month
Alabama      Clay County  2                                    -1.300000
                          3                                    -6.409091
                          4                                   -26.500000
                          5                                   -18.285714
                          6                                   -14.227273
...                                                                  ...
Wyoming      Teton County 7                                   -27.612903
                          8                                   -21.750000
                          9                                   -18.550000
                          10                                  -27.322581
                          11                                  -38.300000

                                 residential_percent_change_from_baseline
sub_region_1 sub_region_2 month
Alabama      Clay County  2                                           NaN
                          3                                           NaN
                          4                                           NaN
                          5                                           NaN
                          6                                           NaN
...                                                                   ...
Wyoming      Teton County 7                                           NaN
                          8                                           NaN
                          9                                           NaN
                          10                                          NaN
                          11                                          NaN

[2436 rows x 6 columns]