# Rahwa's Notebook

In [1]:
# Dependencies and Setup
import os
import csv
import matplotlib.pyplot as plt
import pandas as pd
import numpy as np
import requests
import time
from scipy.stats import linregress

import us

In [2]:
csv_path = "../resources/raw/PopulationAndEducation/Education.csv"
education_df = pd.read_csv(csv_path)
education_df

,FIPS Code,State,Area name,2003 Rural-urban Continuum Code,2003 Urban Influence Code,2013 Rural-urban Continuum Code,2013 Urban Influence Code,"Less than a high school diploma, 1970","High school diploma only, 1970","Some college (1-3 years), 1970",...,"Percent of adults completing some college or associate's degree, 2000","Percent of adults with a bachelor's degree or higher, 2000","Less than a high school diploma, 2014-18","High school diploma only, 2014-18","Some college or associate's degree, 2014-18","Bachelor's degree or higher, 2014-18","Percent of adults with less than a high school diploma, 2014-18","Percent of adults with a high school diploma only, 2014-18","Percent of adults completing some college or associate's degree, 2014-18","Percent of adults with a bachelor's degree or higher, 2014-18"
0,0,US,United States,NaN,NaN,NaN,NaN,"52,373,312","34,158,051","11,650,730",...,27.4,24.4,"26,948,057","59,265,308","63,365,655","68,867,051",12.3,27.1,29.0,31.5
1,1000,AL,Alabama,NaN,NaN,NaN,NaN,"1,062,306","468,269","136,287",...,25.9,19.0,"470,043","1,020,172","987,148","822,595",14.2,30.9,29.9,24.9
2,1001,AL,Autauga County,2.0,2.0,2.0,2.0,"6,611","3,757",933,...,26.9,18.0,"4,204","12,119","10,552","10,291",11.3,32.6,28.4,27.7
3,1003,AL,Baldwin County,4.0,5.0,3.0,2.0,"18,726","8,426","2,334",...,29.3,23.1,"14,310","40,579","46,025","46,075",9.7,27.6,31.3,31.3
4,1005,AL,Barbour County,6.0,6.0,6.0,6.0,"8,120","2,242",581,...,21.3,10.9,"4,901","6,486","4,566","2,220",27.0,35.7,25.1,12.2
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3278,72145,PR,Vega Baja Municipio,1.0,1.0,1.0,1.0,NaN,NaN,NaN,...,21.4,14.4,"11,578","8,571","9,375","7,715",31.1,23.0,25.2,20.7
3279,72147,PR,Vieques Municipio,7.0,12.0,7.0,12.0,NaN,NaN,NaN,...,13.7,10.1,"1,576","2,344","1,067","1,295",25.1,37.3,17.0,20.6
3280,72149,PR,Villalba Municipio,2.0,2.0,2.0,2.0,NaN,NaN,NaN,...,18.0,12.8,"3,733","5,616","2,866","3,073",24.4,36.7,18.7,20.1
3281,72151,PR,Yabucoa Municipio,1.0,1.0,1.0,1.0,NaN,NaN,NaN,...,18.3,12.1,"7,220","5,972","6,281","4,443",30.2,25.0,26.3,18.6
3282,72153,PR,Yauco Municipio,3.0,2.0,2.0,2.0,NaN,NaN,NaN,...,17.8,15.8,"7,236","8,182","4,172","6,386",27.9,31.5,16.1,24.6

In [3]:
csv_path = "../resources/raw/PopulationAndEducation/census2019.csv"
census2019_df = pd.read_csv(csv_path, sep=',' , encoding='latin-1')
census2019_df = census2019_df[["STATE","COUNTY","STNAME","CTYNAME","POPESTIMATE2010","POPESTIMATE2011","POPESTIMATE2012","POPESTIMATE2013","POPESTIMATE2014","POPESTIMATE2015","POPESTIMATE2016","POPESTIMATE2017","POPESTIMATE2018","POPESTIMATE2019"]]
census2019_df

,STATE,COUNTY,STNAME,CTYNAME,POPESTIMATE2010,POPESTIMATE2011,POPESTIMATE2012,POPESTIMATE2013,POPESTIMATE2014,POPESTIMATE2015,POPESTIMATE2016,POPESTIMATE2017,POPESTIMATE2018,POPESTIMATE2019
0,1,0,Alabama,Alabama,4785437,4799069,4815588,4830081,4841799,4852347,4863525,4874486,4887681,4903185
1,1,1,Alabama,Autauga County,54773,55227,54954,54727,54893,54864,55243,55390,55533,55869
2,1,3,Alabama,Baldwin County,183112,186558,190145,194885,199183,202939,207601,212521,217855,223234
3,1,5,Alabama,Barbour County,27327,27341,27169,26937,26755,26283,25806,25157,24872,24686
4,1,7,Alabama,Bibb County,22870,22745,22667,22521,22553,22566,22586,22550,22367,22394
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3188,56,37,Wyoming,Sweetwater County,43574,43986,45002,45157,44948,44719,44222,43464,42858,42343
3189,56,39,Wyoming,Teton County,21296,21414,21624,22315,22773,23047,23234,23384,23269,23464
3190,56,41,Wyoming,Uinta County,21089,20896,20996,20951,20822,20763,20682,20431,20292,20226
3191,56,43,Wyoming,Washakie County,8530,8449,8409,8413,8273,8278,8165,8010,7877,7805
3192,56,45,Wyoming,Weston County,7198,7142,7077,7136,7138,7208,7220,6968,6924,6927

In [4]:
csv_path = "../resources/raw/PopulationAndEducation/census_2010.csv"
census2010_df = pd.read_csv(csv_path, sep=',' , encoding='latin-1')
census2010_df = census2010_df.drop(columns=['SUMLEV','REGION','DIVISION','ESTIMATESBASE2000','CENSUS2010POP','POPESTIMATE2010'])
census2010_df

,STATE,COUNTY,STNAME,CTYNAME,POPESTIMATE2000,POPESTIMATE2001,POPESTIMATE2002,POPESTIMATE2003,POPESTIMATE2004,POPESTIMATE2005,POPESTIMATE2006,POPESTIMATE2007,POPESTIMATE2008,POPESTIMATE2009
0,1,0,Alabama,Alabama,4452173,4467634,4480089,4503491,4530729,4569805,4628981,4672840,4718206,4757938
1,1,1,Alabama,Autauga County,44021,44889,45909,46800,48366,49676,51328,52405,53277,54135
2,1,3,Alabama,Baldwin County,141342,144875,147957,151509,156266,162183,168121,172404,175827,179406
3,1,5,Alabama,Barbour County,29015,28863,28653,28594,28287,28027,27861,27757,27808,27657
4,1,7,Alabama,Bibb County,19913,21028,21199,21399,21721,22042,22099,22438,22705,22941
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3189,56,37,Wyoming,Sweetwater County,37552,36899,37428,37450,38026,38739,39749,41470,42358,44133
3190,56,39,Wyoming,Teton County,18381,18653,18837,19066,19467,19632,20014,20472,20988,21232
3191,56,41,Wyoming,Uinta County,19666,19413,19587,19480,19470,19494,19709,20171,20613,21054
3192,56,43,Wyoming,Washakie County,8252,8068,7988,7976,7960,8022,7979,8169,8229,8423
3193,56,45,Wyoming,Weston County,6627,6487,6578,6610,6646,6594,6717,7033,7133,7266

In [19]:
csv_path = "../resources/raw/PopulationAndEducation/cencounts1990.csv"
census1990_df = pd.read_csv(csv_path)
census1990_df.dropna(inplace = True) 
tempcity = census1990_df["name"].str.split(" ", n = 1, expand = True)
census1990_df["STNAME"]= tempcity[0]
census1990_df["CTYNAME"]= tempcity[1]

for index, row in census1990_df.iterrows():
    state = us.states.lookup(row["STNAME"])
    census1990_df.loc[index, "STNAME"] = str(state)
    
census1990_df

,pop1900,pop1910,pop1920,pop1930,pop1940,pop1950,pop1960,pop1970,pop1980,pop1990,fips,name,STNAME,CTYNAME
0,76212168,92228496,106021537,123202624,132164569,151325798,179323175,203211926,226545805,248709873,0.0,US United States,None,United States
1,1828697,2138093,2348174,2646248,2832961,3061743,3266740,3444165,3893888,4040587,1000.0,AL Alabama,Alabama,Alabama
2,17915,20038,18908,19694,20977,18186,18739,24460,32259,34222,1001.0,AL Autauga County,Alabama,Autauga County
3,13194,18178,20730,28289,32324,40997,49088,59382,78556,98280,1003.0,AL Baldwin County,Alabama,Baldwin County
4,35152,32728,32067,32425,32722,28892,24700,22543,24756,25417,1005.0,AL Barbour County,Alabama,Barbour County
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3218,.,.,.,2003,2543,2593,3062,4823,9355,11172,56039.0,WY Teton County,Wyoming,Teton County
3219,12223,16982,6611,6572,7223,7331,7484,7100,13021,18705,56041.0,WY Uinta County,Wyoming,Uinta County
3220,.,.,3106,4109,5858,7252,8883,7569,9496,8388,56043.0,WY Washakie County,Wyoming,Washakie County
3221,3203,4960,4631,4673,4958,6733,7929,6307,7106,6518,56045.0,WY Weston County,Wyoming,Weston County
3222,369,519,165,200,416,353,420,.,.,.,56047.0,WY Yellowstone Nat. Pk (pt.),Wyoming,Yellowstone Nat. Pk (pt.)

In [29]:
overallcensus_df = pd.merge(census1990_df, census2010_df, on=['STNAME','CTYNAME'])
overallcensus_df = pd.merge(overallcensus_df, census2019_df, on=['STNAME','CTYNAME'])
overallcensus_df[["STNAME","CTYNAME","pop1900","pop1910","pop1920","pop1930","pop1940","pop1950","pop1960","pop1970","pop1980","pop1990","POPESTIMATE2000","POPESTIMATE2001","POPESTIMATE2002","POPESTIMATE2003","POPESTIMATE2004","POPESTIMATE2005","POPESTIMATE2006","POPESTIMATE2007","POPESTIMATE2008","POPESTIMATE2009","POPESTIMATE2010","POPESTIMATE2011","POPESTIMATE2012","POPESTIMATE2013","POPESTIMATE2014","POPESTIMATE2015","POPESTIMATE2016","POPESTIMATE2017","POPESTIMATE2018","POPESTIMATE2019"]]
overallcensus_df

,pop1900,pop1910,pop1920,pop1930,pop1940,pop1950,pop1960,pop1970,pop1980,pop1990,...,POPESTIMATE2010,POPESTIMATE2011,POPESTIMATE2012,POPESTIMATE2013,POPESTIMATE2014,POPESTIMATE2015,POPESTIMATE2016,POPESTIMATE2017,POPESTIMATE2018,POPESTIMATE2019
0,1828697,2138093,2348174,2646248,2832961,3061743,3266740,3444165,3893888,4040587,...,4785437,4799069,4815588,4830081,4841799,4852347,4863525,4874486,4887681,4903185
1,17915,20038,18908,19694,20977,18186,18739,24460,32259,34222,...,54773,55227,54954,54727,54893,54864,55243,55390,55533,55869
2,13194,18178,20730,28289,32324,40997,49088,59382,78556,98280,...,183112,186558,190145,194885,199183,202939,207601,212521,217855,223234
3,35152,32728,32067,32425,32722,28892,24700,22543,24756,25417,...,27327,27341,27169,26937,26755,26283,25806,25157,24872,24686
4,18498,22791,23144,20780,20155,17987,14357,13812,15723,16576,...,22870,22745,22667,22521,22553,22566,22586,22550,22367,22394
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3166,8455,11575,13640,18165,19407,22017,17920,18391,41723,38823,...,43574,43986,45002,45157,44948,44719,44222,43464,42858,42343
3167,.,.,.,2003,2543,2593,3062,4823,9355,11172,...,21296,21414,21624,22315,22773,23047,23234,23384,23269,23464
3168,12223,16982,6611,6572,7223,7331,7484,7100,13021,18705,...,21089,20896,20996,20951,20822,20763,20682,20431,20292,20226
3169,.,.,3106,4109,5858,7252,8883,7569,9496,8388,...,8530,8449,8409,8413,8273,8278,8165,8010,7877,7805
3170,3203,4960,4631,4673,4958,6733,7929,6307,7106,6518,...,7198,7142,7077,7136,7138,7208,7220,6968,6924,6927

In [30]:
census_state = overallcensus_df.loc[(overallcensus_df["STNAME"] == overallcensus_df["CTYNAME"])]
census_state
census_state.reset_index(drop=True, inplace=True)
census_state

,pop1900,pop1910,pop1920,pop1930,pop1940,pop1950,pop1960,pop1970,pop1980,pop1990,...,POPESTIMATE2010,POPESTIMATE2011,POPESTIMATE2012,POPESTIMATE2013,POPESTIMATE2014,POPESTIMATE2015,POPESTIMATE2016,POPESTIMATE2017,POPESTIMATE2018,POPESTIMATE2019
0,1828697,2138093,2348174,2646248,2832961,3061743,3266740,3444165,3893888,4040587,...,4785437,4799069,4815588,4830081,4841799,4852347,4863525,4874486,4887681,4903185
1,63592,64356,55036,59278,72524,128643,226167,300382,401851,550043,...,713910,722128,730443,737068,736283,737498,741456,739700,735139,731545
2,122931,204354,334162,435573,499261,749587,1302161,1770900,2718215,3665228,...,6407172,6472643,6554978,6632764,6730413,6829676,6941072,7044008,7158024,7278717
3,1311564,1574449,1752204,1854482,1949387,1909511,1786272,1923295,2286435,2350725,...,2921964,2940667,2952164,2959400,2967392,2978048,2989918,3001345,3009733,3017804
4,1485053,2377549,3426861,5677251,6907387,10586223,15717204,19953134,23667902,29760021,...,37319502,37638369,37948800,38260787,38596972,38918045,39167117,39358497,39461588,39512223
5,539700,799024,939629,1035791,1123296,1325089,1753947,2207259,2889964,3294394,...,5047349,5121108,5192647,5269035,5350101,5450623,5539215,5611885,5691287,5758736
6,908420,1114756,1380631,1606903,1709242,2007280,2535234,3031709,3107576,3287116,...,3579114,3588283,3594547,3594841,3594524,3587122,3578141,3573297,3571520,3565287
7,184735,202322,223003,238380,266505,318085,446292,548104,594338,666168,...,899593,907381,915179,923576,932487,941252,948921,956823,965479,973764
8,278718,331069,437571,486869,663091,802178,763956,756510,638333,606900,...,605226,619800,634924,650581,662328,675400,685815,694906,701547,705749
9,278718,331069,437571,486869,663091,802178,763956,756510,638333,606900,...,605226,619800,634924,650581,662328,675400,685815,694906,701547,705749
10,278718,331069,437571,486869,663091,802178,763956,756510,638333,606900,...,605226,619800,634924,650581,662328,675400,685815,694906,701547,705749
11,278718,331069,437571,486869,663091,802178,763956,756510,638333,606900,...,605226,619800,634924,650581,662328,675400,685815,694906,701547,705749
12,278718,331069,437571,486869,663091,802178,763956,756510,638333,606900,...,605226,619800,634924,650581,662328,675400,685815,694906,701547,705749
13,278718,331069,437571,486869,663091,802178,763956,756510,638333,606900,...,605226,619800,634924,650581,662328,675400,685815,694906,701547,705749
14,278718,331069,437571,486869,663091,802178,763956,756510,638333,606900,...,605226,619800,634924,650581,662328,675400,685815,694906,701547,705749
15,278718,331069,437571,486869,663091,802178,763956,756510,638333,606900,...,605226,619800,634924,650581,662328,675400,685815,694906,701547,705749
16,528542,752619,968470,1468211,1897414,2771305,4951560,6789443,9746324,12937926,...,18845537,19053237,19297822,19545621,19845911,20209042,20613477,20963613,21244317,21477737
17,2216331,2609121,2895832,2908506,3123723,3444578,3943116,4589575,5463105,6478216,...,9711881,9802431,9901430,9972479,10067278,10178447,10301890,10410330,10511131,10617423
18,154001,191874,255881,368300,422770,499794,632772,768561,964691,1108229,...,1363963,1379329,1394804,1408243,1414538,1422052,1427559,1424393,1420593,1415872
19,161772,325594,431866,445032,524873,588637,667191,712567,943935,1006749,...,1570746,1583910,1595324,1611206,1631112,1651059,1682380,1717715,1750536,1787065
20,4821550,5638591,6485280,7630654,7897241,8712176,10081158,11113976,11426518,11430602,...,12840503,12867454,12882510,12895129,12884493,12858913,12820527,12778828,12723071,12671821
21,2516462,2700876,2930390,3238503,3427796,3934224,4662498,5193669,5490224,5544159,...,6490432,6516528,6537703,6568713,6593644,6608422,6634304,6658078,6695497,6732219
22,2231853,2224771,2404021,2470939,2538268,2621073,2757537,2824376,2913808,2776755,...,3050745,3066336,3076190,3092997,3109350,3120960,3131371,3141550,3148618,3155070
23,1470495,1690949,1769257,1880999,1801028,1905299,2178611,2246578,2363679,2477574,...,2858190,2869225,2885257,2893212,2900475,2909011,2910844,2908718,2911359,2913314
24,2147174,2289905,2416630,2614589,2845627,2944806,3038156,3218706,3660777,3685296,...,4348181,4369821,4386346,4404659,4414349,4425976,4438182,4452268,4461153,4467673
25,1381625,1656388,1798509,2101593,2363880,2683516,3257022,3641306,4205900,4219973,...,4544532,4575625,4600972,4624527,4644013,4664628,4678135,4670560,4659690,4648794
26,694466,742371,768014,797423,847226,913774,969265,992048,1124660,1227928,...,1327629,1328284,1327729,1328009,1330513,1328262,1331317,1334612,1339057,1344212
27,1188044,1295346,1449661,1631526,1821244,2343001,3100689,3922399,4216975,4781468,...,5788645,5839419,5886992,5923188,5957283,5985562,6003323,6023868,6035802,6045680
28,2805346,3366416,3852356,4249614,4316721,4690514,5148578,5689170,5737037,6016425,...,6566307,6613583,6663005,6713315,6762596,6794228,6823608,6859789,6882635,6892503
29,2420982,2810173,3668412,4842325,5256106,6371766,7823194,8875083,9262078,9295297,...,9877510,9882412,9897145,9913065,9929848,9931715,9950571,9973114,9984072,9986857
30,1751394,2075708,2387125,2563953,2792300,2982483,3413864,3804971,4075970,4375099,...,5310828,5346143,5376643,5413479,5451079,5482032,5522744,5566230,5606249,5639632
31,1551270,1797114,1790618,2009821,2183796,2178914,2178141,2216912,2520638,2573216,...,2970548,2978731,2983816,2988711,2990468,2988471,2987938,2988510,2981020,2976149
32,3106665,3293335,3404055,3629367,3784664,3954653,4319813,4676501,4916686,5117073,...,5995974,6010275,6024367,6040715,6056202,6071732,6087135,6106670,6121623,6137428
33,243329,376053,548889,537606,559456,591024,674767,694409,786690,799065,...,990697,997316,1003783,1013569,1021869,1030475,1040859,1052482,1060665,1068778
34,1066300,1192214,1296372,1377963,1315834,1325510,1411330,1483493,1569825,1578385,...,1829542,1840672,1853303,1865279,1879321,1891277,1905616,1915947,1925614,1934408
35,42335,81875,77407,91058,110247,160083,285278,488738,800493,1201833,...,2702405,2712730,2743996,2775970,2817628,2866939,2917563,2969905,3027341,3080156
36,411588,430572,443083,465293,491524,533242,606921,737681,920610,1109252,...,1316762,1320202,1324232,1326622,1333341,1336350,1342307,1348787,1353465,1359711
37,1883669,2537167,3155900,4041334,4160165,4835329,6066782,7168164,7364823,7730188,...,8799446,8828117,8844942,8856972,8864525,8867949,8870827,8885525,8886025,8882190
38,195310,327301,360350,423317,531818,681187,951023,1016000,1302894,1515069,...,2064552,2080450,2087309,2092273,2089568,2089291,2091630,2091784,2092741,2096829
39,7268894,9113614,10385227,12588066,13479142,14830192,16782304,18236967,17558072,17990455,...,19399878,19499241,19572932,19624447,19651049,19654666,19633428,19589572,19530351,19453561
40,1893810,2206287,2559123,3170276,3571623,4061929,4556155,5082059,5881766,6628637,...,9574323,9657592,9749476,9843336,9932887,10031646,10154788,10268233,10381615,10488084
41,319146,577056,646872,680845,641935,619636,632446,617761,652717,638800,...,674715,685225,701176,722036,737401,754066,754434,754942,758080,762062
42,4157545,4767121,5759394,6646697,6907612,7946627,9706397,10652017,10797630,10847115,...,11539336,11544663,11548923,11576684,11602700,11617527,11634370,11659650,11676341,11689100
43,790391,1657155,2028283,2396040,2336434,2233351,2328284,2559229,3025290,3145585,...,3759944,3788379,3818814,3853214,3878187,3909500,3926331,3931316,3940235,3956971
44,413536,672765,783389,953786,1089684,1521341,1768687,2091385,2633105,2842321,...,3837491,3872036,3899001,3922468,3963244,4015792,4089976,4143625,4181886,4217737
45,6302115,7665111,8720017,9631350,9900180,10498012,11319366,11793909,11863895,11881643,...,12711160,12745815,12767118,12776309,12788313,12784826,12782275,12787641,12800922,12801989
46,428556,542610,604397,687497,713346,791896,859488,946725,947154,1003464,...,1053959,1053649,1054621,1055081,1055936,1056065,1056770,1055673,1058287,1059361
47,1340316,1515400,1683724,1738765,1899804,2117027,2382594,2590516,3121820,3486703,...,4635649,4671994,4717354,4764080,4823617,4891938,4957968,5021268,5084156,5148714
48,401570,583888,636547,692849,642961,652740,680514,665507,690768,696004,...,816166,823579,833566,842316,849129,853988,862996,872868,878698,884659
49,2020616,2184789,2337885,2616556,2915841,3291718,3567089,3923687,4591120,4877185,...,6355311,6399291,6453898,6494340,6541223,6591170,6646010,6708799,6771631,6829174
50,3048710,3896542,4663228,5824715,6414824,7711194,9579677,11196730,14229191,16986510,...,25241971,25645629,26084481,26480266,26964333,27470056,27914410,28295273,28628666,28995881
51,276749,373351,449396,507847,550310,688862,890627,1059273,1461037,1722850,...,2775332,2814384,2853375,2897640,2936879,2981835,3041868,3101042,3153550,3205958
52,343641,355956,352428,359611,359231,377747,389881,444330,511456,562758,...,625879,627049,626090,626210,625214,625216,623657,624344,624358,623989
53,1854184,2061612,2309187,2421851,2677773,3318680,3966949,4648494,5346818,6187358,...,8023699,8101155,8185080,8252427,8310993,8361808,8410106,8463587,8501286,8535519
54,518103,1141990,1356621,1563396,1736191,2378963,2853214,3409169,4132156,4866692,...,6742830,6826627,6897058,6963985,7054655,7163657,7294771,7423362,7523869,7614893
55,958800,1221119,1463701,1729205,1901974,2005552,1860421,1744237,1949644,1793477,...,1854239,1856301,1856872,1853914,1849489,1842050,1831023,1817004,1804291,1792147
56,2069042,2333860,2632067,2939006,3137587,3434575,3951777,4417731,4705767,4891769,...,5690475,5705288,5719960,5736754,5751525,5760940,5772628,5790186,5807406,5822434
57,92531,145965,194402,225565,250742,290529,330066,332416,469557,453588,...,564487,567299,576305,582122,582531,585613,584215,578931,577601,578759